# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'roi_reconstruction_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(780, 676)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.l_path = QtWidgets.QLineEdit(Form)
        self.l_path.setObjectName("l_path")
        self.horizontalLayout.addWidget(self.l_path)
        self.pb_save = QtWidgets.QPushButton(Form)
        self.pb_save.setObjectName("pb_save")
        self.horizontalLayout.addWidget(self.pb_save)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pb_settings = QtWidgets.QPushButton(Form)
        self.pb_settings.setObjectName("pb_settings")
        self.gridLayout.addWidget(self.pb_settings, 0, 5, 1, 1)
        self.pb_br = QtWidgets.QPushButton(Form)
        self.pb_br.setObjectName("pb_br")
        self.gridLayout.addWidget(self.pb_br, 1, 0, 1, 1)
        self.l_bry = QtWidgets.QLineEdit(Form)
        self.l_bry.setMaximumSize(QtCore.QSize(100, 16777215))
        self.l_bry.setObjectName("l_bry")
        self.gridLayout.addWidget(self.l_bry, 1, 2, 1, 1)
        self.l_brz = QtWidgets.QLineEdit(Form)
        self.l_brz.setMaximumSize(QtCore.QSize(100, 16777215))
        self.l_brz.setObjectName("l_brz")
        self.gridLayout.addWidget(self.l_brz, 1, 3, 1, 1)
        self.pb_start = QtWidgets.QPushButton(Form)
        self.pb_start.setObjectName("pb_start")
        self.gridLayout.addWidget(self.pb_start, 1, 5, 1, 1)
        self.l_tly = QtWidgets.QLineEdit(Form)
        self.l_tly.setMaximumSize(QtCore.QSize(100, 16777215))
        self.l_tly.setObjectName("l_tly")
        self.gridLayout.addWidget(self.l_tly, 0, 2, 1, 1)
        self.l_tlx = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_tlx.sizePolicy().hasHeightForWidth())
        self.l_tlx.setSizePolicy(sizePolicy)
        self.l_tlx.setMaximumSize(QtCore.QSize(100, 16777215))
        self.l_tlx.setBaseSize(QtCore.QSize(0, 0))
        self.l_tlx.setObjectName("l_tlx")
        self.gridLayout.addWidget(self.l_tlx, 0, 1, 1, 1)
        self.pb_tl = QtWidgets.QPushButton(Form)
        self.pb_tl.setObjectName("pb_tl")
        self.gridLayout.addWidget(self.pb_tl, 0, 0, 1, 1)
        self.l_brx = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_brx.sizePolicy().hasHeightForWidth())
        self.l_brx.setSizePolicy(sizePolicy)
        self.l_brx.setMaximumSize(QtCore.QSize(100, 16777215))
        self.l_brx.setBaseSize(QtCore.QSize(0, 0))
        self.l_brx.setObjectName("l_brx")
        self.gridLayout.addWidget(self.l_brx, 1, 1, 1, 1)
        self.l_tlz = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_tlz.sizePolicy().hasHeightForWidth())
        self.l_tlz.setSizePolicy(sizePolicy)
        self.l_tlz.setMaximumSize(QtCore.QSize(100, 16777215))
        self.l_tlz.setObjectName("l_tlz")
        self.gridLayout.addWidget(self.l_tlz, 0, 3, 1, 1)
        self.label_status = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_status.sizePolicy().hasHeightForWidth())
        self.label_status.setSizePolicy(sizePolicy)
        self.label_status.setText("")
        self.label_status.setObjectName("label_status")
        self.gridLayout.addWidget(self.label_status, 0, 4, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 1, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.widget = AnnotationWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Save to:"))
        self.pb_save.setText(_translate("Form", "Browse"))
        self.pb_settings.setText(_translate("Form", "Settings"))
        self.pb_br.setText(_translate("Form", "Set bottom right point"))
        self.pb_start.setText(_translate("Form", "Start"))
        self.pb_tl.setText(_translate("Form", "Set top left point"))

from VISoR_Reconstruction.tools.common.annotation_widget.annotation_widget import AnnotationWidget
