# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'open_dialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(608, 312)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.line_edit_mdf = QtWidgets.QLineEdit(Dialog)
        self.line_edit_mdf.setObjectName("line_edit_mdf")
        self.gridLayout.addWidget(self.line_edit_mdf, 3, 1, 1, 1)
        self.pb_mdf = QtWidgets.QPushButton(Dialog)
        self.pb_mdf.setObjectName("pb_mdf")
        self.gridLayout.addWidget(self.pb_mdf, 3, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.pb_mimg = QtWidgets.QPushButton(Dialog)
        self.pb_mimg.setObjectName("pb_mimg")
        self.gridLayout.addWidget(self.pb_mimg, 1, 2, 1, 1)
        self.pb_fimg = QtWidgets.QPushButton(Dialog)
        self.pb_fimg.setObjectName("pb_fimg")
        self.gridLayout.addWidget(self.pb_fimg, 0, 2, 1, 1)
        self.line_edit_fimg = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_edit_fimg.sizePolicy().hasHeightForWidth())
        self.line_edit_fimg.setSizePolicy(sizePolicy)
        self.line_edit_fimg.setObjectName("line_edit_fimg")
        self.gridLayout.addWidget(self.line_edit_fimg, 0, 1, 1, 1)
        self.line_edit_mimg = QtWidgets.QLineEdit(Dialog)
        self.line_edit_mimg.setObjectName("line_edit_mimg")
        self.gridLayout.addWidget(self.line_edit_mimg, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.pb_fdf = QtWidgets.QPushButton(Dialog)
        self.pb_fdf.setObjectName("pb_fdf")
        self.gridLayout.addWidget(self.pb_fdf, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.line_edit_fdf = QtWidgets.QLineEdit(Dialog)
        self.line_edit_fdf.setObjectName("line_edit_fdf")
        self.gridLayout.addWidget(self.line_edit_fdf, 2, 1, 1, 1)
        self.pb_mp = QtWidgets.QPushButton(Dialog)
        self.pb_mp.setObjectName("pb_mp")
        self.gridLayout.addWidget(self.pb_mp, 5, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.line_edit_fp = QtWidgets.QLineEdit(Dialog)
        self.line_edit_fp.setObjectName("line_edit_fp")
        self.gridLayout.addWidget(self.line_edit_fp, 4, 1, 1, 1)
        self.pb_fp = QtWidgets.QPushButton(Dialog)
        self.pb_fp.setObjectName("pb_fp")
        self.gridLayout.addWidget(self.pb_fp, 4, 2, 1, 1)
        self.line_edit_mp = QtWidgets.QLineEdit(Dialog)
        self.line_edit_mp.setObjectName("line_edit_mp")
        self.gridLayout.addWidget(self.line_edit_mp, 5, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 6, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pb_mdf.setText(_translate("Dialog", "Browse"))
        self.label_5.setText(_translate("Dialog", "Fixed points"))
        self.label_4.setText(_translate("Dialog", "Moving deformation field"))
        self.pb_mimg.setText(_translate("Dialog", "Browse"))
        self.pb_fimg.setText(_translate("Dialog", "Browse"))
        self.label_3.setText(_translate("Dialog", "Fixed deformation field"))
        self.label_2.setText(_translate("Dialog", "Moving image"))
        self.pb_fdf.setText(_translate("Dialog", "Browse"))
        self.label.setText(_translate("Dialog", "Fixed image"))
        self.pb_mp.setText(_translate("Dialog", "Browse"))
        self.label_6.setText(_translate("Dialog", "Moving points"))
        self.pb_fp.setText(_translate("Dialog", "Browse"))

