# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'surface_registration_ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1059, 747)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.avFix = AnnotationWidget(self.centralwidget)
        self.avFix.setMinimumSize(QtCore.QSize(100, 0))
        self.avFix.setObjectName("avFix")
        self.horizontalLayout.addWidget(self.avFix)
        self.avMove = AnnotationWidget(self.centralwidget)
        self.avMove.setMinimumSize(QtCore.QSize(100, 0))
        self.avMove.setObjectName("avMove")
        self.horizontalLayout.addWidget(self.avMove)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(430, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(200)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.pbElastix = QtWidgets.QPushButton(self.centralwidget)
        self.pbElastix.setEnabled(False)
        self.pbElastix.setObjectName("pbElastix")
        self.horizontalLayout_2.addWidget(self.pbElastix)
        self.pbView = QtWidgets.QPushButton(self.centralwidget)
        self.pbView.setEnabled(False)
        self.pbView.setObjectName("pbView")
        self.horizontalLayout_2.addWidget(self.pbView)
        self.pbEdit = QtWidgets.QPushButton(self.centralwidget)
        self.pbEdit.setEnabled(False)
        self.pbEdit.setObjectName("pbEdit")
        self.horizontalLayout_2.addWidget(self.pbEdit)
        self.pbAddPoint = QtWidgets.QPushButton(self.centralwidget)
        self.pbAddPoint.setEnabled(False)
        self.pbAddPoint.setObjectName("pbAddPoint")
        self.horizontalLayout_2.addWidget(self.pbAddPoint)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1059, 31))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionchange_templete = QtWidgets.QAction(MainWindow)
        self.actionchange_templete.setObjectName("actionchange_templete")
        self.actionexport_points = QtWidgets.QAction(MainWindow)
        self.actionexport_points.setEnabled(False)
        self.actionexport_points.setObjectName("actionexport_points")
        self.actionexport_registrated_image = QtWidgets.QAction(MainWindow)
        self.actionexport_registrated_image.setEnabled(False)
        self.actionexport_registrated_image.setObjectName("actionexport_registrated_image")
        self.actionimport_points = QtWidgets.QAction(MainWindow)
        self.actionimport_points.setObjectName("actionimport_points")
        self.menu.addAction(self.actionopen)
        self.menu.addAction(self.actionchange_templete)
        self.menu.addAction(self.actionexport_points)
        self.menu.addAction(self.actionexport_registrated_image)
        self.menu.addAction(self.actionimport_points)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "fix"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "move"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pbElastix.setText(_translate("MainWindow", "run elastix"))
        self.pbView.setText(_translate("MainWindow", "view"))
        self.pbEdit.setText(_translate("MainWindow", "edit"))
        self.pbAddPoint.setText(_translate("MainWindow", "add point"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.actionopen.setText(_translate("MainWindow", "open"))
        self.actionchange_templete.setText(_translate("MainWindow", "change templete"))
        self.actionexport_points.setText(_translate("MainWindow", "export points"))
        self.actionexport_registrated_image.setText(_translate("MainWindow", "export registrated image"))
        self.actionimport_points.setText(_translate("MainWindow", "import points"))

from interactive_registration.annotation_widget import AnnotationWidget
